name: plantcv-environment
channels:
  - conda-forge
  - default
dependencies:
  - numpy
  - toolz
  - matplotlib
  - pandas
  - opencv
  - pip:
    - git+https://github.com/danforthcenter/plantcv.git
